### ISSUE TITLE
Add XEP name column

### ISSUE THREAD

**Issue by lovetox** [pulkomandy/xmpp-doap#10]
Hi,

It would be nice if beside the XEP number there would be the name of the XEP in a column.
Users who are scanning the list otherwise need to click every XEP and lookup what it does, instead of getting a view Keywords.

Im not sure if this is in the scope of the project, because i dont know if this is possible with xsl transformations.

The idea would be rather then adding the information into the DOAP file itself, maybe put a xeps.xml (which is probably available on xmpp.org) into the folder and xsl pulls and matches the informaton from there?

**Comment by pulkomandy** [comment]
Note for later: someone did some work on the jdev channel but doesn't have a github account. See what they did and if it can be used (I'm unsure if their solution will work for rendering the XML directly in a web browser, but I didn't look very closely)

**Comment by pulkomandy** [comment]
Proposed patches:

https://xmpp.labs.navlost.eu/upload/4f883a857d1fd410d36f3b5a55395c7b1d631fe5/mlHcvPRS68ttlw3Xh7QIk2v4oxKpSgb5N5pab6hm/0001-Add-classes-for-styling-of-XEP-revision.patch
https://xmpp.labs.navlost.eu/upload/4f883a857d1fd410d36f3b5a55395c7b1d631fe5/k4ceq5sWCRrmUNO8KBwyA9fUNpVYkb7Rez8XkWz0/0002-Add-XEP-revision-details.patch

They don't work in xsltproc, but I'm ok with that. More annoyingly, they don't work in web browsers due to cross-site scripting rules. It would need a change to xmpp.org to allow loading the XML files from other sites. Where can we discuss that with the people hosting xmpp.org?

Also, is it wise to load all XEPs everytime someone views a DOAP file in a browser? Would it be more efficient to have a summary of all XEPs in a single XML file? Where would that single file be hosted?

**Comment by pulkomandy** [comment]
Fixed with 2619a7c0c5e1df969143835e5b0c097b0f7e1787 and some commits around it.

However, for this to work we need XMPP.org to serve xeplist.xml with an http header that allows loading it from another origin. It seems this is configured here: https://github.com/xsf/xmpp.org/blob/master/deploy/xsf.conf

**Comment by cal0pteryx** [comment]
https://xmpp.org/extensions/xeplist.xml is now served with the appropriate header, and https://pulkomandy.github.io/xmpp-doap/samples/movim.xml for example works :tada: 

Note that browser CORS caching may interfere here, so if it doesn't work, try a browser that hasn't previously failed.

**Comment by cal0pteryx** [comment]
Seems Chome/Chromium does not support cross-origin xslt/xml requests: https://bugs.chromium.org/p/chromium/issues/detail?id=1035198

It works fine in Firefox (tested with Firefox 104.0).

**Comment by cal0pteryx** [comment]
@pulkomandy this issue can be closed, since there is nothing left to do from our side.

**Comment by pulkomandy** [comment]
Yes, I think this is as good as it can get for now. Thanks for the reminder :)
